name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd be1-api-and-scibert
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip only application folder
        run: |
          cd be1-api-and-scibert
          zip -r ../release.zip . -x "*.git*"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: meta-analysis-backend
          package: release.zip
